In [1]:
## How Faster is Numpy? ##
import time
import numpy as np

size_of_vec = 1000000

def pure_python_version():
    t1 =time.time()
    x = range(size_of_vec)
    y = range(size_of_vec)
    z = [x[i]+y[i] for i in range (len(x))]
    return time.time() - t1

def numpy_version():
    t2 =time.time()
    x = np.arange(size_of_vec)
    y = np.arange(size_of_vec)
    z = x+y
    return time.time() - t2

t1 = pure_python_version()
t2 = numpy_version()

print(f'''Waktu running pure python adalah {round(t1,4)} detik.\nWaktu running versi numpy adalah {round(t2,4)} detik.\nNumpy di contoh ini {(round((t1/t2)/4))}kali lebih cepat!''')

Waktu running pure python adalah 0.4766 detik.
Waktu running versi numpy adalah 0.01 detik.
Numpy di contoh ini 12kali lebih cepat!


In [2]:
## Creating Numpy from Python List ##
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
my_list3 = [[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]]
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [7]:
## np.arange ##
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
## np.zeros ##
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
## np.ones ##
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
## np.eye ##
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
## np.linspace ##
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
## random.rand ##
np.random.rand(2)

array([0.36523817, 0.09002958])

In [17]:
np.random.rand(5,5)

array([[0.08245875, 0.76515014, 0.54272875, 0.48879215, 0.73166238],
       [0.53193862, 0.316979  , 0.07039955, 0.57439072, 0.90988511],
       [0.27805608, 0.06719844, 0.13097707, 0.18098928, 0.51352148],
       [0.37170024, 0.21449163, 0.86499009, 0.49059434, 0.13136356],
       [0.60303452, 0.43173303, 0.69948456, 0.98113759, 0.45966722]])

In [18]:
## random.randn ##
np.random.randn(2)

array([ 0.78367748, -0.39055345])

In [19]:
np.random.randn(5,5)

array([[ 0.56769103,  0.99137076,  0.36144594, -0.48976054, -0.41501301],
       [ 0.32396414, -0.62532306, -0.34036881, -1.25673431,  0.61561698],
       [-0.23982984, -0.84984984,  0.86167669,  0.52372105,  0.00451841],
       [ 1.90984313, -0.21900118,  2.80050779,  0.2048668 , -0.63044372],
       [ 0.33062004, -0.64670786,  0.35402509,  0.88636087,  0.25590064]])

In [20]:
## random.randint ##
np.random.randint(1,100)

78

In [21]:
np.random.randint(1,100,10)

array([36,  5, 66, 11, 27, 78, 50, 61, 55,  5])

In [22]:
## Shape ##
my_list = [1,2,3]
array_1d = np.array(my_list)

my_list2 = [[1,2,3],[4,5,3],[7,8,9]]
array_2d = np.array(my_list2)

my_list3 = [[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]]
array_3d = np.array(my_list3)

In [23]:
array_1d.shape

(3,)

In [24]:
array_2d.shape

(3, 3)

In [25]:
array_3d.shape

(3, 3, 3)

In [26]:
## Reshape ##
x = np.random.rand(10)
x

array([0.55487693, 0.65240707, 0.47605851, 0.84986408, 0.49003647,
       0.82065036, 0.49051472, 0.75952163, 0.11399002, 0.18321525])

In [27]:
x.shape

(10,)

In [28]:
x.reshape(1,10)

array([[0.55487693, 0.65240707, 0.47605851, 0.84986408, 0.49003647,
        0.82065036, 0.49051472, 0.75952163, 0.11399002, 0.18321525]])

In [29]:
x.reshape(1,10).shape

(1, 10)

In [30]:
x.reshape(2,5)

array([[0.55487693, 0.65240707, 0.47605851, 0.84986408, 0.49003647],
       [0.82065036, 0.49051472, 0.75952163, 0.11399002, 0.18321525]])

In [31]:
x.reshape(2,5).shape

(2, 5)

In [32]:
x.reshape(10,1)

array([[0.55487693],
       [0.65240707],
       [0.47605851],
       [0.84986408],
       [0.49003647],
       [0.82065036],
       [0.49051472],
       [0.75952163],
       [0.11399002],
       [0.18321525]])

In [33]:
x.reshape(10,1).shape

(10, 1)

In [34]:
y = np.random.rand(5,5)
y

array([[0.24058914, 0.57677939, 0.19442771, 0.80652704, 0.67851093],
       [0.16791757, 0.83664383, 0.62359781, 0.95286847, 0.70748335],
       [0.93922626, 0.47255031, 0.15007747, 0.41397493, 0.72401315],
       [0.63237264, 0.74296767, 0.72151889, 0.37705875, 0.07509559],
       [0.02891672, 0.76840432, 0.64984091, 0.52553687, 0.29977432]])

In [35]:
y.shape

(5, 5)

In [36]:
y.reshape(-1)

array([0.24058914, 0.57677939, 0.19442771, 0.80652704, 0.67851093,
       0.16791757, 0.83664383, 0.62359781, 0.95286847, 0.70748335,
       0.93922626, 0.47255031, 0.15007747, 0.41397493, 0.72401315,
       0.63237264, 0.74296767, 0.72151889, 0.37705875, 0.07509559,
       0.02891672, 0.76840432, 0.64984091, 0.52553687, 0.29977432])

In [37]:
y.reshape(-1).shape

(25,)

In [38]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [39]:
array_3d.reshape(-1).shape

(27,)

In [40]:
## max, min, argmax, argmin ##
z = np.random.randint(0,50,10)
z

array([18, 36, 43, 40, 38, 18, 12, 18, 26, 16])

In [41]:
z.max()

43

In [42]:
z.argmax()

2

In [43]:
z.min()

12

In [44]:
z.argmin()

6

In [45]:
## dtype ##
z.dtype

dtype('int32')

In [46]:
y.dtype

dtype('float64')

In [47]:
## Indexing ##
arr = np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [48]:
# Get value at an index
arr[5]

6

In [49]:
# Get value in a range
arr[1:10]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr[0:20:2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [52]:
## Slicing ##
# setting a value with an index range
arr[0:3]=80
arr

array([80, 80, 80,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [53]:
# reset aray
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [58]:
slice_of_arr[:]=80
slice_of_arr

array([80, 80, 80, 80, 80])

In [59]:
arr

array([80, 80, 80, 80, 80,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
arr_copy = arr.copy()
arr_copy

array([80, 80, 80, 80, 80,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [61]:
slice_of_arr_copy= arr_copy[0:5]
slice_of_arr_copy[:]=70
slice_of_arr_copy

array([70, 70, 70, 70, 70])

In [62]:
arr_copy

array([70, 70, 70, 70, 70,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [63]:
arr

array([80, 80, 80, 80, 80,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [66]:
## Indexing a 2D array ##
arr_2d = np.array(([10,14,9],[25,13,19],[28,15,30]))

arr_2d

array([[10, 14,  9],
       [25, 13, 19],
       [28, 15, 30]])

In [67]:
# indexing row
arr_2d[1]

array([25, 13, 19])

In [68]:
# getting individual element value
arr_2d[1][0]

25

In [69]:
arr_2d[1,0]

25

In [76]:
# 2D array slicing
arr_2d[:2,1:]

array([[14,  9],
       [13, 19]])

In [77]:
arr_2d[:,2]

array([ 9, 19, 30])

In [78]:
## Fancy Indexing ##
arr

array([80, 80, 80, 80, 80,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [79]:
# normal indexing
[arr[2],arr[5],arr[9]]

[80, 5, 9]

In [80]:
# fancy indexing
arr[[2,5,9]]

array([80,  5,  9])

In [82]:
arr[[9,5,2]]

array([ 9,  5, 80])

In [83]:
arr_2d[[1,2]]

array([[25, 13, 19],
       [28, 15, 30]])

In [84]:
## Conditional Selection ##
arr

array([80, 80, 80, 80, 80,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [85]:
arr >= 15

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [86]:
bool_arr = arr>=15

In [87]:
bool_arr

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [89]:
bool_arr.dtype

dtype('bool')

In [90]:
arr[bool_arr]

array([80, 80, 80, 80, 80, 15, 16, 17, 18, 19])